grafana:
  readinessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1

  livenessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 30
    failureThreshold: 12
    successThreshold: 1
