apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  namespace: {{ .Release.Namespace }}
  labels:
    app: productcatalogue
spec:
  type: ClusterIP
  selector:
    app: productcatalogue
  ports:
    - name: http
      port: 8020
      targetPort: 8020
      protocol: TCP