apiVersion: v1
kind: Service
metadata:
  name: shopfront
  namespace: {{ .Release.Namespace }}
  labels:
    app: shopfront
spec:
  type: ClusterIP
  selector:
    app: shopfront
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      protocol: TCP